### ISSUE TITLE
Locks up when changing from 68020 to 68000 (when pressing Reset).

### ISSUE THREAD

**Issue by windale** [Chips-fr/uae4arm-rpi#1]
I have made two profiles, an A500 one
68000
OCS
7Mhz
512k Chip & 512k Slow memory
More Compatible

And a A1200 one
68020
AGA
14Mhz
2mb Chip & 8mb Fast memory
Hardrive (ClassicWB & WHDLoad)

I played some WHDLoad games on the A1200 profile then decided to switch to my A500 profile (I clicked the profile and pressed Load). But when pressing 'Reset' it locks up the whole system and I have to turn the Raspberry Pi Off/On. It does this every time.

**Comment by amigagamer** [comment]
@windale I've done a lot of profile switching for performance testing and have never run into this problem.  If you start straight into your A500 profile does it work ok?

**Comment by windale** [comment]
The lock up also happens the other way round from what I listed above. I can reproduce it every time. If I load my A500 profile and press reset, see the workbench hand prompt. Go back to the menu GUI, select my A1200 profile, load it then press reset and it locks up.
