### ISSUE TITLE
Launch directly into savestate

### ISSUE THREAD

**Issue by GrethTom** [Chips-fr/uae4arm-rpi#11]
It is well practiced to launch directly into a config file which load the emulator directly.  A number of other emulators have support to launch directly into a savestate using a command line parameter but currently cannot find anything for UAE4ARM.

**Comment by Chips-fr** [comment]
This is possible since quite a long time. You can even override config to start directly into emulation mode instead of gui.

Ex:

uae4arm -config=conf/test.uae -statefile=savestates/test.uss -s use_gui=0
