### ISSUE TITLE
Joypad control in the Emulator Menu

### ISSUE THREAD

**Issue by GrethTom** [Chips-fr/uae4arm-rpi#12]
A number of games do not require a keyboard or mouse.  When going to the menu you may only want to make a simple change or reset but having to grab the mouse/keyboard is not ideal.  Would it be possible to have the joypad able to control the menu up to the point where you need to enter text?

**Comment by PanosPl** [comment]
Having at least a way to map the Quit or the F12 to the pad would be awesome. Mapping the mouse to the right analog stick would make this port heavenly.

**Comment by Chips-fr** [comment]
Close in latest commit
