### ISSUE TITLE
Does not start emulation after rpi-update (with firmware 4.4y)

### ISSUE THREAD

**Issue by midwan** [Chips-fr/uae4arm-rpi#22]
I noticed that if I upgrade my RPi3 with the latest stable firmware, using:
$ sudo apt-get install rpi-update
$ sudo rpi-update

then launch uae4arm-rpi2, in the config screen the mouse input is very sluggish. Moving the mouse pointer around is very slow, as if something is taking up all the cpu in the background.

Using the previous firmware the problem does not exist.

I've tested with v0.5 of uae4arm-rpi2, both the binary package and compiled from source. The system is a Raspian Jessie, fully upgraded to the latest packages. Please let me know if you need any more details.

**Comment by Chips-fr** [comment]
Don't use rpi-update unless you know what you're doing...
Use sudo apt-get update or even dis-update

**Comment by midwan** [comment]
In that case, "I know what I'm doing"... :)

I can always roll back to my backup, this was meant to be reported in order to look into it and perhaps fix it, since this firmware is now pushed as the new "stable" version to the users.

To be clear, if I launch the emulator after the config screen, it doesn't seem to suffer from the same problem (i.e. in the emulation environment itself, the mouse pointer moves normally). This only seems to affect the config screen of uae4arm from what I've seen so far.

**Comment by midwan** [comment]
I've updated the title to be a little more specific. :)

**Comment by midwan** [comment]
I had a chance to do a full recompile of the sources with the headers from the latest firmware today. Unfortunately, besides the slow mouse movement in the menu, it also does not boot when using a normal 3.1 kickstart and the stock A1200 configuration.

**Comment by midwan** [comment]
Update: the slow movement in the menu is only apparent in a Minibian installation (it's a minimal Raspbian distro). On a normal Raspbian, the mouse movement is normal. However, in both of those environments it fails to Start the emulation after the firmware upgrade. After the user clicks on Start in the config window, a black screen appears. The F12 key does not respond so you cannot go back to the config screen. Let me know if you need any more details to help you reproduce this.

**Comment by midwan** [comment]
This doesn't seem to be an issue anymore, so I'm closing it.
