### ISSUE TITLE
I cannot launch amiga cd32 iso game

### ISSUE THREAD

**Issue by dakota72** [Chips-fr/uae4arm-rpi#23]
Hi,
I cannot launch the iso game,
I tried with GUI and also without GUI,
and the result is a error: The selected system ROM requires a 68EC020 or later
but I try with 68020 and 68030 with the same result.
I launch the emulator with:  
./uae4arm -conf=conf/cd32_1.uae -s use_gui=no
my conf file is in attach
thanks in advance.
dak

[cd32_1.uae.txt](https://github.com/Chips-fr/uae4arm-rpi/files/406726/cd32_1.uae.txt)

**Comment by Chips-fr** [comment]
Your kickstart config looks wrong. You should not have 2 kickstart but only one and the CD32 as external.

kickstart_rom_file=$(FILE_PATH)/Kickstart v3.1 rev 40.60 (1993)(Commodore)(CD32).rom
kickstart_ext_rom_file=$(FILE_PATH)/CD32.rom
