### ISSUE TITLE
Slow sound in uaegfx modes.

### ISSUE THREAD

**Issue by martblek** [Chips-fr/uae4arm-rpi#25]
Tested few .mod files in Delitracker.
In PAL modes all ok.
last uae4arm version compiled from git.
RPi2 1GHz.

**Comment by lubomyr** [comment]
I fixed it in android port. You can add similar changes
https://github.com/lubomyr/uae4arm/commit/de7615fc12ce5289ad219564a68c3678a8670b55

**Comment by martblek** [comment]
I modified sources like in your commit.
Now in lowest uaegfx resolutions / under 800x600x8/ seems to be all ok,
but in highest resolutions same "slow" problem.

**Comment by lubomyr** [comment]
that's bad :(
When i fixed it i tested only with one resolution 640x400x32
Now I tried to test it with higher resolution with my device:
640x400, 640x480, 800x480, 800x600, 960x540 (x8, x16, x32) - works perfect
with 1024x600 - sometimes i can hear small micropauses
with 1024x768 and higher  - these pauses more intensive :(
but sound rate the same, not "slower".
Maybe it related with performance of device. But I'm not sure.

**Comment by lubomyr** [comment]
In non-JIT mode
1024x600, and 1024x768 (x8, x16, x32) - works perfect
with higher mode - the same micropauses

**Comment by martblek** [comment]
Tested with ArchlinuxArm and RPI2 overclocked to 1GHz.
Sound through HDMI with config.txt

gpu_mem=256
hdmi_drive=2
hdmi_group=1
hdmi_mode=19

i try to change hdmi_mode coz it set to 50Hz.
I hear micropauses and some sound distortions in higher resolutions.
Sometimes few alsa underruns if i quit emulator.
