### ISSUE TITLE
Keyboard and joystick broken for RPi/gles

### ISSUE THREAD

**Issue by escalade** [Chips-fr/uae4arm-rpi#26]
I'm using LibreELEC which has no X server, so compiling with platform=gles. This  commit breaks both keyboard and joystick:

https://github.com/Chips-fr/uae4arm-rpi/commit/c7db909cafc1f878cff849903a4e15d3c5a9299a

Tested with an RPi3. Rolling back to the previous commit (a33d65d) works fine.

The SDL version used is vanfanel/SDL-1.2.15-raspberrypi.

**Comment by Chips-fr** [comment]
But this commit isn't soling this issue ?
https://github.com/Chips-fr/uae4arm-rpi/commit/1472101b95d0f54c01555b2fb4a10da23f372266
Don't use vanfanel SDL, normally you don't need it...

**Comment by escalade** [comment]
No, it does not. Looks like the SDL input simply stopped working after c7db909. I've tested with platform=generic-sdl as well, same result.I do need vanfanel SDL as I am running uae4arm under LibreELEC which has no X server, so I need the dispmanx backend.

**Comment by Chips-fr** [comment]
dispmanX has nothing to do with X server... gles works well on raspbian without X server and without vanfallen SDL.

**Comment by escalade** [comment]
Ok, but in any case I need it for Dosbox. But everything works fine before the said commit so Vanfanel SDL shouldn't be the issue.

**Comment by Chips-fr** [comment]
Note that gles is less tested, has less options, and is less polished... hence I don't recommend it on Rpi.

**Comment by escalade** [comment]
Joystick works now, but keyboard still doesn't work :)
