### ISSUE TITLE
Keyboard broken

### ISSUE THREAD

**Issue by escalade** [Chips-fr/uae4arm-rpi#27]
Joystick works now after https://github.com/Chips-fr/uae4arm-rpi/commit/e669dd7f26013deb28e098dd723fdc78100b2938 but keyboard is still broken... :)

**Comment by escalade** [comment]
Relevant output from uae4arm:

`**Unknown keycode to use, will use keysym**
Joystick 0 : Wireless Controller
    Buttons: 14 Axis: 16 Hats: 1
starting sound thread..
`

**Comment by Chips-fr** [comment]
You means keyboard is somewhat working but not all key ? looks like the case...

**Comment by escalade** [comment]
Ah you're right! Keys are actually working except function keys :)
