### ISSUE TITLE
Holding down RShift and tapping "S" closes the emulator

### ISSUE THREAD

**Issue by midwan** [Chips-fr/uae4arm-rpi#30]
I noticed a strange behavior, it's there in both my fork and yours:

If you hold down the Right Shift key, and while keeping it pressed you tap the "S" key, the emulator shuts down -  no messages are shown in the console, so I'm not sure if it crashed or just quit.

If you do the same with the Right Shift + "D", then the status leds pop up on the bottom right hand corner. RShift + D hides them again (if you tap D quickly) so it looks like a toggle button.

I couldn't find those shortcuts in the code, so I'm not sure if it's "expected behavior" or a bug.

Are you aware of these?

**Comment by Chips-fr** [comment]
Thoses shortcuts from pandora are still present in gui_handle_events

**Comment by midwan** [comment]
Thanks, I've located them now. I'll try removing them to see if it improves things, I don't think they need to be there for the RPi port anyway (you can always go in the config GUI to trigger them).
