### ISSUE TITLE
Compiling Error on RPi 3 with new makefile

### ISSUE THREAD

**Issue by dakota72** [Chips-fr/uae4arm-rpi#32]
Hi,
I try to compile with new makefile but an error stopped the compiler when create custom.o
{standard input}: Assembler messages:
{standard input}:29832: Error: selected processor does not support ARM mode `ubfx r1,r4,#19,#5'
{standard input}:29833: Error: selected processor does not support ARM mode `ubfx r2,r4,#10,#6'
arm processor is wrong? but I a have on rpi3.
regards,
dak

**Comment by Chips-fr** [comment]
Which distribution and target ?
It woks well in raspbian jessie and rpi2 (the main one i compile..)...

**Comment by dakota72** [comment]
retropie 3.8.1
uname -a: 
Linux retropie 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux

**Comment by midwan** [comment]
This would happen if you selected "rpi1" as the platform, since that target CPU does not support ARMV6T2 instructions such as ubfx.

**Comment by dakota72** [comment]
the default value of PLATFORM is rpi3 in Makefile 
also I tried to force PLATFORM to rpi3...

I don't know why it don't work.

**Comment by midwan** [comment]
Are you sure you're using @Chips-fr fork? His makefile has rpi2 as the default target and does not include the rpi3 platform at all.

I've added that in my fork and it does compile normally: https://github.com/midwan/uae4arm-rpi

**Comment by dakota72** [comment]
>  https://github.com/midwan/uae4arm-rpi
this makefile is different to Chiprs-fr makefile 
this a diff:
6c6
<       CPU_FLAGS += -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard
---
>       CPU_FLAGS += -mcpu=cortex-a53 -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -funsafe-math-optimizations
11a12
>       USE_PICASSO96 = 1
13c14
<       CPU_FLAGS += -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard
---
>       CPU_FLAGS += -mcpu=cortex-a7 -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -funsafe-math-optimizations
18a20
>       USE_PICASSO96 = 1
65a68,71
> ifeq ($(USE_PICASSO96), 1)
>       MORE_CFLAGS += -DPICASSO96
> endif

but both don't work :(
the old makefile instead works fine.
which gcc you use? and which kernel?

**Comment by midwan** [comment]
You can't just mix Makefiles and expect it to work (it might, but then you're lucky).
If you want to try out my fork, you should get the whole bunch and use its Makefile. ;-)

**Comment by midwan** [comment]
Update: I apologize for not seeing this earlier, it appears my Makefile was incorrect. Some flags were not passed to the compiler and that created the errors you reported originally.

I've updated it now and tested it again, it seems to work as expected. I compiled a version for rpi3 and rpi1 without problems.

**Comment by dakota72** [comment]
ok midwan, now it works fine! 
many thanks for your fix! 
you can close the issue! ;)

**Comment by midwan** [comment]
Thanks for confirming! :)
