### ISSUE TITLE
Embedded version

### ISSUE THREAD

**Issue by quartexNOR** [Chips-fr/uae4arm-rpi#35]
Hi Chips

Im looking into linking UAE4Arm with either Ultibo or Nucleus RTOS for the Raspberry PI 3. Basically remove linux from the equation and run UAE4Arm as the only process (except for the RTOS subsystems naturally).

But I think we need some input from you on this.
Would you mind dropping me a line and talking it over?

**Comment by Chips-fr** [comment]
You can always ask.

**Comment by quartexNOR** [comment]
Hi again, and thanks for the reply.

First, im used to c++ builder, so the linux stuff is a bit alien at the moment. But I have ordered a ton of books on the subject, so with a bit of study I should get up to speed. Although dismanx seems to be deprecated when i googled it (?).

Having looked at the code, in my mind I would imagine that dispmanx and the sdl dependencies would have to be removed. The code elsewhere seems fairly well organized, with memory read/write isolated, which should make porting easier. 
Perhaps rem-out the audio to begin with and focus on getting it to run and render to a dib first of all.
Am i completely off the map here or does this sound in line with the reality of the codebase?

For the embedded system I have setup the normal packages: audio, filesystem, memory manager, graphics, usb and wifi. The raspberry SoC is well known by now, with the exception of the video decoder. There i have to buy the pre-compiled .lib files and link in the driver. But live video is not really a priority at this point.

So down to brass tax:
 1. Would you be available to help me out a bit if i get stuck?
 2. Could you explain how communication between UAE and 68k code can be established?
 3. What would be the best way to go about turning UAE into a library, one that exports symbols for rendering, audio, io etc. so UAE can be used from other languages and also be extended by these?

Note: The idea here is that I would like to write some standard functions for exposing methods into the amiga side. On the Amiga side I would have to write a corresponding library file so 68k programs can tap into these API's.

The reason I ask is because uae already does this (the berkley socket library option).
How exactly this is done (filesystem entry? Rom patch?) i have yet to figure out, but perhaps you could shed some light on the subject?

Question number 3 basically follows the same line of thought, but here im interested in ripping out the platform dependent aspects and expose these as normal symbols. Any program that wants to embed uae would have to provide implementation for these functions so the linker can match them up.

Well, any feedback or ideas is welcome!
Also, if i could ask you for input once in a while would really be helpful.

Best regards

Jon Lennart Aasenden
Quartex Norway :)

**Comment by Chips-fr** [comment]
Note that uae4arm is not really linux only oriented, it should be easily portable on any OS supporting SDL. Hence it has more dependency with SDL than Linux...
DispmanX is not deprecated, it's proprietary. In uae4arm You can use others platform (see makefile) which don't rely on dispmanX for the display but on SDL or GLES if you prefer (but result is better with dispmanX on Rpi).
I think the first things would be to remove all SDL/dispmanX dependencies... it should be quite easy.
I didn't implemented uae4arm but only ported it to rpi (TomB did it for pandora), so i don't know much for it's internal management.
What you want to do look like close to what is needed for retroarch.
I have no idea regarding your question about exposing method into amiga side. As I said I didn't implemented uae4arm (moreover those part are even inherit from winuae i think).

**Comment by quartexNOR** [comment]
Ok, thanks for the feedback and info on SDL dependency.
I will start tinkering with it shortly.

Cheers!
