### ISSUE TITLE
disk.cpp code stops keyboard led status code

### ISSUE THREAD

**Issue by n0rt0nthec4t** [Chips-fr/uae4arm-rpi#39]
Seems to be a bug in the latest commit for the disk.cpp file which causes the status led code to not update. Traced error to update_drive_gui() but still trying to work out why the following if statement always fails so function exits before calling gui_led

  if (!force && drv->state == gui_data.drive_motor[num]
          && drv->cyl == gui_data.drive_track[num]
          && side == gui_data.drive_side
          && drv->crc32 == gui_data.crc32[num]
          && writ == gui_data.drive_writing[num]
          && !_tcscmp (gui_data.df[num], currprefs.floppyslots[num].df))
          return;

**Comment by n0rt0nthec4t** [comment]
Seems that the "num" variable being passed into the update_drive_gui() function exceeds the number of allocated floppies

suggest commenting out the below

if (num <= currprefs.nr_floppies) 
    return;

**Comment by Chips-fr** [comment]
It doesn't change anything...
Even if i modified the function to always set led they only get small blinking... so something should put them back to off in the latest software but i didn't find which code... commenting other ioctl doesn't solve this. Strange.

**Comment by n0rt0nthec4t** [comment]
I'll play around with it some more. I had changed the led code in gui_led

**Comment by Chips-fr** [comment]
ioctl(0, KDGETLED, &kbd_led_status); needs to have a unsigned char for kbd_led_status. At least using this solve the ver num.
