### ISSUE TITLE
Trolls AGA Graphic bugs at intro

### ISSUE THREAD

**Issue by Syon1** [Chips-fr/uae4arm-rpi#49]
Running RetroPie 4.1 with the latest uae4arm core on a rpi3.

When starting Trolls AGA from .adf, im unable to get the intro part correct. I have tried all settings in the UI that i can find without any good results. When i change Blitter to Normal it do get better but still a lot of gfx glitches. 

use_gui=no
kickstart_rom_file=/home/pi/RetroPie/BIOS/Kick31.rom
kickstart_rom_file_id=1483A091,KS ROM v3.1 (A1200)
kickstart_ext_rom_file=
flash_file=
floppy0=/home/pi/RetroPie/roms/amiga/Trolls (AGA) (Disk 1 of 2).adf
floppy1=/home/pi/RetroPie/roms/amiga/Trolls (AGA) (Disk 2 of 2).adf
floppy2=
floppy3=
nr_floppies=2
floppy_speed=100
sound_output=normal
sound_channels=stereo
sound_stereo_separation=7
sound_stereo_mixing_delay=0
sound_frequency=44100
sound_interpol=none
sound_filter=off
sound_filter_type=standard
sound_volume_cd=20
cachesize=8192
joyport0=mouse
joyport0autofire=none
joyportfriendlyname0=Nubs as mouse
joyportname0=MOUSE0
joyport1=joy1
joyport1autofire=none
joyport1mode=djoy
joyportfriendlyname1=retronicdesign.com Retro Joystick Adapter v2.1
joyportname1=JOY1
bsdsocket_emu=false
synchronize_clock=true
key_for_menu=293
gfx_framerate=0
gfx_width=640
gfx_height=256
gfx_width_windowed=320
gfx_height_windowed=240
gfx_width_fullscreen=640
gfx_height_fullscreen=270
gfx_lores=false
gfx_resolution=hires
gfx_correct_aspect=1
gfx_fullscreen_ratio=100
kbd_led_num=-1
kbd_led_scr=-1
kbd_led_cap=-1
immediate_blits=true
fast_copper=true
ntsc=false
show_leds=true
chipset=aga
chipset_refreshrate=0.000000
collision_level=full
fastmem_size=2
z3mem_size=0
z3mem_start=0x10000000
bogomem_size=0
gfxcard_size=0
gfxcard_type=ZorroIII
chipmem_size=4            (I know that is should be 2, but then you only get 1mb chip. Bug?)
finegrain_cpu_speed=1024
cpu_type=68ec020
cpu_model=68020
cpu_compatible=false
cpu_24bit_addressing=true
rtg_modes=0x502

Keep the good work up =)

**Comment by jdca** [comment]
I got glitches in the game nitro when using cpu_type=68ec020 so i switched to 68000

**Comment by Chips-fr** [comment]
Not reproduce with latest version.
