### ISSUE TITLE
2mb chip in GUI shows up as 4 in .uae file

### ISSUE THREAD

**Issue by Syon1** [Chips-fr/uae4arm-rpi#50]
When you are setting up a Basic 1200 with 2mb chip ram i noticed that in the saved .uae file it looks like this:

chipmem_size=4

If you edit the line inside the .uae file to =2 and save it, uae4arm GUI shows 1mb chip ram.

Dont know if this is a bug or if it should be like that?

**Comment by lg-oainger** [comment]
Hi Syon1,

I believe that number is a multiple of 512KB (e.g. 2x 512KB = 1MB or 4x 512MB = 2MB)

**Comment by osvaldolove** [comment]
Hi Syon1,

I believe that number is a multiple of 512KB (e.g. 2x 512KB = 1MB or 4x 512MB = 2MB)

**Comment by Syon1** [comment]
That could be it. 

It seems like it is only behaving that way with CHIP memory and not the other ones.

But as long as it works, im happy =)

**Comment by Chips-fr** [comment]
Yes it is saved by chunk of 512 KB since it's the granularity of RAM configuration you could find on real Amiga.

See:
p->chipmem_size = dummyint * 0x80000;
