### ISSUE TITLE
Last commits do not compile on Raspberry Pi 3 with Raspbian

### ISSUE THREAD

**Issue by Sandokan71** [Chips-fr/uae4arm-rpi#57]
I can't compile last repository versions. Last working commit it seems the one done on February 9, 2018

**Comment by Chips-fr** [comment]
What is the error you got ?

**Comment by Sandokan71** [comment]
Hello,

in attach the printscreen when I compile with last commit. Let me know if
you need more informations.

Thanks






2018-03-01 17:01 GMT+01:00 Chips-fr <notifications@github.com>:

**Comment by Sandokan71** [comment]
Here a compile test for 8ff1fd4  on 29 Jan PandTomB and Chips-fr Added JIT
for FPU.









2018-03-01 21:13 GMT+01:00 Elvis Ciafrone <elvis.ciafrone@gmail.com>:

**Comment by Chips-fr** [comment]
I don't see anything. Try copy & paste...
Note that I just succeed to compile from a fresh git clone on raspbian.

**Comment by Sandokan71** [comment]
Other commit works ok. For example this
one 6839afb7351e450a7ab4acf760658b08035f144d it is ok.

I installet raspbian from scratch and update it. Then downloaded libs and
compiled from a fresh git-clone last commit:

Here a copy&paste:

pi@raspberrypi:~/uae4arm-rpi-last $ make
(cd capsimg ; ./bootstrap ; ./configure ; make ; cp capsimg.so ../ )
Boostrapping capsimg...
Running autoheader
./bootstrap: 6: ./bootstrap: autoheader: not found
/bin/sh: 1: ./configure: not found
make[1]: ingresso nella directory "/home/pi/uae4arm-rpi-last/capsimg"
make[1]: *** Nessun obiettivo specificato e nessun makefile trovato.
Arresto.
make[1]: uscita dalla directory "/home/pi/uae4arm-rpi-last/capsimg"
cp: impossibile eseguire stat di 'capsimg.so': File o directory non
esistente
Makefile:112: set di istruzioni per l'obiettivo "capsimg.so" non riuscito
make: *** [capsimg.so] Errore 1

Following what appens with an older one:

pi@raspberrypi:~/uae4arm-rpi-8ff1fd42972a14dc4ae99560fca72b2b9176e4eb $ make
g++ `sdl-config --cflags` -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard
-DRASPBERRY `xml2-config --cflags` -DCPU_arm -DARMV6_ASSEMBLY -DPANDORA
-DWITH_INGAME_WARNING -DROM_PATH_PREFIX=\"./\" -DDATA_PREFIX=\"./data/\"
-DSAVE_PREFIX=\"./saves/\" -DUSE_SDL -DPICASSO96 -DUSE_ARMNEON
-DCAPSLOCK_DEBIAN_WORKAROUND -DARMV6T2 -DUSE_JIT_FPU -I/opt/vc/include
-I/opt/vc/include/interface/vmcs_host/linux
-I/opt/vc/include/interface/vcos/pthreads -Isrc -Isrc/od-pandora
-Isrc/threaddep -Isrc/menu -Isrc/include -Isrc/archivers -Isrc/od-pandora
-Wno-unused -Wno-format  -DGCCCONSTFUNC="__attribute__((const))"
-fexceptions -fpermissive -Ofast -fomit-frame-pointer
-fsingle-precision-constant -finline -fno-builtin   -c -o src/fpp_native.o
src/fpp_native.cpp
src/fpp_native.cpp:27:8: error: ‘uae_u32’ does not name a type
 static uae_u32 dhex_nan[]   ={0xffffffff, 0x7fffffff};
        ^~~~~~~
src/fpp_native.cpp:28:38: error: ‘dhex_nan’ was not declared in this scope
 static double *fp_nan    = (double *)dhex_nan;
                                      ^~~~~~~~
src/fpp_native.cpp:42:8: error: ‘uae_u32’ does not name a type
 static uae_u32 fpu_mode_control = 0;
        ^~~~~~~
src/fpp_native.cpp:46:26: error: variable or field ‘fpp_set_mode’ declared
void
 static void fpp_set_mode(uae_u32 mode_control)
                          ^~~~~~~
src/fpp_native.cpp:46:26: error: ‘uae_u32’ was not declared in this scope
<incorporato>: set di istruzioni per l'obiettivo "src/fpp_native.o" non
riuscito
make: *** [src/fpp_native.o] Errore 1





2018-03-01 21:45 GMT+01:00 Chips-fr <notifications@github.com>:

**Comment by Chips-fr** [comment]
You are mixing two different issue. I think it's better to focus on first one.
looks like you're missing autoheader tool.
I think it's part of autoconf, you can try to install it:

sudo apt-get install autoconf

then redo make.

**Comment by Sandokan71** [comment]
Works!
Thanks


Have a nice day/night!




2018-03-01 22:27 GMT+01:00 Chips-fr <notifications@github.com>:

**Comment by Chips-fr** [comment]
Good. I should have install it for another project and didn't catch it was now mandatory.
I will add it in dependency in readme.
