### ISSUE TITLE
Lha CRC errors with JIT enabled

### ISSUE THREAD

**Issue by henrikstengaard** [Chips-fr/uae4arm-rpi#59]
![uae4arm_lha_crc_error_jit](https://user-images.githubusercontent.com/9459668/39394300-e861f984-4ad0-11e8-9bda-bde2bf57e2e5.jpg)

CRC errors occur when extracting lha archives with JIT enabled.
It works fine without CRC errors, if JIT is disabled.

### Steps to reproduce

1. Extract attached file uae4arm_lha_crc_error_jit.zip and launch UAE4ARM with added directory containing the files. Config file is included. Make sure JIT is enabled.
2. Type "lha -m1 x pfs3_53.lha sys:t/".
3. Wait for lha to break with crc errors.

[uae4arm_lha_crc_error_jit.zip](https://github.com/Chips-fr/uae4arm-rpi/files/1957485/uae4arm_lha_crc_error_jit.zip)

**Comment by henrikstengaard** [comment]
Using lha22.lha from aminet does solve the crc errors.

For a quick fix, I'm going to update from lha 2.15 to lha 2.2 to solve the crc errors I have encountered with UAE4ARM and JIT enabled for cpu 68030 and fpu 68882.

**Comment by Chips-fr** [comment]
I tested and got it working in current version so i will close this old issue.
