### ISSUE TITLE
Md5sum crashes or exits with JIT enabled

### ISSUE THREAD

**Issue by henrikstengaard** [Chips-fr/uae4arm-rpi#60]
Crash or exit when running md5sum a few times.

### Steps to reproduce

1. Extract attached file uae4arm_crash_md5sum_jit.zip and launch UAE4ARM with added directory containing the files. Config file is included. Make sure JIT is enabled.
2. Type "md5sum -b md5sum".
3. Repeat step 2 a few times and UAE4ARM crashes or exits.

[uae4arm_crash_md5sum_jit.zip](https://github.com/Chips-fr/uae4arm-rpi/files/1957489/uae4arm_crash_md5sum_jit.zip)

**Comment by Chips-fr** [comment]
Not reproduce with latest version.
