### ISSUE TITLE
PS3 controller mis-mapped in RetroPie 4.4

### ISSUE THREAD

**Issue by fru1tl00p** [Chips-fr/uae4arm-rpi#61]
I'm trying to use a PS3 controller with UAE4ARM and retropie 4.4 but I get some mismapped buttons.

The left analog stick works fine which is great! However the fire button is mapped to 'up' on the dpad, making it difficult to do everthing with one hand. Also L is mapped to jump, and dpad 'down' is mapped to fire 2.

What I would like to do is remap those to A/B/X/Y, but so far haven't been able to configure pandora to do that, I'm not even sure if it's possible?

The WinUAE PS3 mappings are all fine, so something has gone awry in the port?

A/B/X/Y are 0,1,2,3 on the PS3 controller. Yet for some reason it thinks the dpad is 0,1,2,3.

Edit, so found these settings, but they don't seem to do anything...

pandora.button1=2
pandora.button2=1
pandora.autofire_button=3
pandora.jump=-1

What does the =x signify? The button number on the controller or a preset action in UAE?

Raspberry Pi Model 3 B+
RetroPie 4.4 from SD image from official site
Raspberry Pi official charger
UAE4ARM installed using the RetroPie interface

**Comment by Chips-fr** [comment]
Now it is available as a libretro core to avoid such issues...
