### ISSUE TITLE
Raspberry Pi Version 4

### ISSUE THREAD

**Issue by edwinkelly** [Chips-fr/uae4arm-rpi#65]
I am considering upgrading from my Raspberry Pi 3 to a Raspberry Pi 4.  From what I can
tell I am uncertain if the version of uae4arm-rpi that I am running on my Pi 3 is compatible with the Pi 4.  If it is compatible (and perhaps I just need to recompile it on the Pi 4), could you confirm this or perhaps let me know when a Pi 4 compatible version
might be available?  Thanks.

**Comment by sidick** [comment]
I'm not sure this project is still being updated, I've not seen any commits for a while, it could be worth you trying Amiberry in the meantime as they do have Pi 4 support (though not in an actual release yet)

**Comment by Chips-fr** [comment]
the rpi2 target works for pi 2, 3 & 4
