### ISSUE TITLE
CRT shaders?

### ISSUE THREAD

**Issue by sphaero** [Chips-fr/uae4arm-rpi#66]
I noticed shaders are used. Any pointers how to get CRT shaders used?

see: https://github.com/RetroPie/RetroPie-Setup/wiki/Shaders-and-Smoothing

There's a whole bunch of them here as well: https://github.com/guestrr/FS-UAE-Shaders

**Comment by sphaero** [comment]
I found the SHADER_SUPPORT flag in the makefile. But uncommenting had no effect. Are the shaders also for raspberry pi's?

**Comment by Chips-fr** [comment]
You need to uncomment SHADER_SUPPORT flag and compile the gles target. All of this was working on raspberry pi at some time.
It use an hardcoded shader, so it needs some work if you want to integrate other shader...

**Comment by sphaero** [comment]
It fails to compile with:
```
Error: selected processor does not support `ubfx r1,r3,#19,#5' in ARM mode
```
I'm running on a RPI3 (ARMv7 Processor rev 4 (v7l))

**Comment by sphaero** [comment]
Ah, it's the makefile not detecting an rpi correctly. Just uncommented `ifneq ($(findstring raspberrypi,$(shell uname -a)),)`.

Now faced with a 
```
glGetError 0x501
GL error: glTexSubImage2D 501
```

**Comment by Chips-fr** [comment]
Found a correction.
Note that the shader code is not very polished.
