### ISSUE TITLE
Enabling JIT makes sound crackle / video slow down sometimes (works better without JIT).

### ISSUE THREAD

**Issue by windale** [Chips-fr/uae4arm-rpi#7]
JIT also doesn’t work properly. According to TomB (who implemented JIT into the Pandora port), JIT is only useful when using CPU speed “Fastest”, but if you do this then a lot of Games/Demos end up having crackling sound and also slower video. I couldn’t see any difference when I turned JIT off. Also when leaving a WHDLoad Game/Demo and go back to ClassicWB you can hear a fast repeating sound that lasts a few seconds. 'Retrofan' also confirmed this.

Tested on Raspberry Pi 2 with RetroPie v3.2.1. I also updated UAE4Arm from ‘Source’.

**Comment by windale** [comment]
Tried the latest update (Nov 16) but JIT still doesn't improve anything. It just starts to make the sound crackle and the video slow down. When I turn JIT off it's fine again.

**Comment by Chips-fr** [comment]
Not reproduce.

**Comment by windale** [comment]
It doesn't happen on everything, only some games/demos. The performance is much better without JIT.
