### ISSUE TITLE
Libretro compilation failed

### ISSUE THREAD

**Issue by fobellianne** [Chips-fr/uae4arm-rpi#70]
![Screenshot_2023-06-15_09-24-13](https://github.com/Chips-fr/uae4arm-rpi/assets/136599591/2743c450-859f-42dc-9813-a6a945292e68)

The libretro compilation failed with this message :
/usr/bin/ld: ./src/newcpu.o(.text+0xad8): unresolvable R_ARM_CALL relocation against symbol `abort@@LIBC_2.4'
collect2: error: ld return 1 exit status
make: *** [Makefile.libretro:233: uae4arm_libretro.so] Error 1

My config is Raspberry pi3b+ on raspbian distrib

**Comment by Chips-fr** [comment]
In your log ld complained about -fPIC option but i've cheched and it's enabled in all config in Makefile.libretro and especially the rpi 3:
https://github.com/Chips-fr/uae4arm-rpi/blob/177c2f0e892adf2603ada9b150e31beffe0f76c3/Makefile.libretro#L55

I got same issue as you if i remove fPIC option.

Can you confirm your command line ? gcc version ? and the g++ command line you see in the log when you compile ?
