### ISSUE TITLE
Custom button/key mapping not working

### ISSUE THREAD

**Issue by vretro** [Chips-fr/uae4arm-rpi#8]
The custom key/button mapping feature of UAE4ARM is not functioning, but would be so useful if it did.

**Comment by GrethTom** [comment]
Patch is now and waiting review/approval from Chips.  Once in, please test and let me know if you get any issues.

**Comment by padremayi** [comment]
Any news?

**Comment by GrethTom** [comment]
Chips is currently reviewing if the changes are possible while keeping the Pandora elements as standard as possible.

**Comment by padremayi** [comment]
Clear, thanks
