### ISSUE TITLE
[RPI2] Issues with some games

### ISSUE THREAD

**Issue by nemo93** [Chips-fr/uae4arm-rpi#9]
first of all many thanks for making this emulator a reality on the Pi. I'm so glad to be able to play my old favorite games from The Bitmap Bros or Sensible!!! It works very nicely and flawlessly.

Yet I do have few issues with some games that I'm listing hereafter. As those games with the same kick roms work perfectly with WinUAE I'm pretty sure issue is at the emu level.

* ~~Banshee (AGA, kick31, 2MB RAM). Works great but the scoreboard/live panel on the left is not there. Instead there's just nothing but black. Different versions tested but same outcome each time.~~
=> this is now fixed!!!

* First Samurai (ECS, kick13, 512k RAM, 512k slow). Playable but intro/demo is buggy and can even freeze the emulation at some point. If you pass the demo then game plays fine. Different versions tested but same outcome each time.

* Second Samurai AGA (AGA, kick31, 2MB RAM). Doesn't launch, Guru meditation. Different versions tested but same outcome each time. (Edit: the ECS/OCS version works nicely)

* ~~New York Warriors (ECS, kick13, 512k RAM, 512k slow). Launch, asked for Disk #2 then throw a software error/guru meditation after disk has been inserted. Different versions tested but same outcome each time.~~

* ~~Panza Kick Boxing (ECS, kick13, 512k RAM, 512k slow). Launch, asked for Disk #B then get stuck. Different versions tested but same outcome each time.~~

* ~~Push Over (ECS, kick13, 512k RAM, 512k slow). Launch, asked for Disk #2 then goes in a loop keep asking for second disk. Different versions tested but same outcome each time.~~

* ~~Project X (ECS, kick13, 512k RAM, 512k slow). Launch but get stuck right before first stage starts. It get stuck right after a screen with text mission is displayed. Different versions tested but same outcome each time.~~ (Edit: the Special Edition '93 works nicely)

that's a few games only. Many others work just like in the old days :)
cheers,

**Comment by dakota72** [comment]
Hi,
I cannot launch iso game ...
I tried also Banshee game with your configuration but don't work! :(
which conf are you used?
thanks, 
dak,
